#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : acpica-unix2
Version  : 3.12.2021
Release  : 502
URL      : file:///aot/build/clearlinux/packages/acpica-unix2/acpica-unix2-v3.12.2021.tar.gz
Source0  : file:///aot/build/clearlinux/packages/acpica-unix2/acpica-unix2-v3.12.2021.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: acpica-unix2-bin = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Build EFI ACPICA Utilities
The EFI porting of the ACPICA utilities can be built with GNU EFI and EDK2.
However, the porting has only been tested in a Linux environment.

%package bin
Summary: bin components for the acpica-unix2 package.
Group: Binaries

%description bin
bin components for the acpica-unix2 package.


%prep
%setup -q -n acpica-unix2
cd %{_builddir}/acpica-unix2

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1638672826
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1f content
export CFLAGS="-O3"
export CXXFLAGS="-O3"
#
export FCFLAGS="-O3"
export FFLAGS="-O3"
export CFFLAGS="-O3"
#
export LDFLAGS="-O3"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
## altflags1f end
make  %{?_smp_mflags}    V=1 VERBOSE=1


%install
export SOURCE_DATE_EPOCH=1638672826
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/acpibin
/usr/bin/acpidump
/usr/bin/acpiexamples
/usr/bin/acpiexec
/usr/bin/acpihelp
/usr/bin/acpisrc
/usr/bin/acpixtract
/usr/bin/iasl
