#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : acpica-unix2
Version  : 20161222
Release  : 14
URL      : https://acpica.org/sites/acpica/files/acpica-unix2-20161222.tar.gz
Source0  : https://acpica.org/sites/acpica/files/acpica-unix2-20161222.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: acpica-unix2-bin
BuildRequires : bison
BuildRequires : flex

%description
/*
* Miscellaneous instructions for building and using the iASL compiler.
*/
Last update 9 December 2013.

%package bin
Summary: bin components for the acpica-unix2 package.
Group: Binaries

%description bin
bin components for the acpica-unix2 package.


%prep
%setup -q -n acpica-unix2-20161222

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484418814
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1484418814
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/acpibin
/usr/bin/acpidump
/usr/bin/acpiexamples
/usr/bin/acpiexec
/usr/bin/acpihelp
/usr/bin/acpinames
/usr/bin/acpisrc
/usr/bin/acpixtract
/usr/bin/iasl
